### ISSUE TITLE
Layout is not mobile friendly

### ISSUE THREAD

**Issue by behanc** [andjor/lfpbot-issue#4]
Layout is not mobile friendly (see below) - it makes it harder to get a quick overview. I believe that most might view the /lfp on the phone why it should be optimzed for mobile over desktop in my mind.

![image](https://github.com/andjor/lfpbot-issue/assets/7113942/974671fa-6058-4e7b-827e-c4675d7a13f9)

**Comment by andjor** [comment]
I wanted the elements in the list to be aligned, that is why there is so much spacing now. Perhaps removing the year helps a bit. And a dynamic way to grow with longer usernames. If you have ideas for another design, they are welcome ☺️

**Comment by behanc** [comment]
Can it output emojis?

If so, maybe something like this then:

1. ✅ kaapaaf (01-17 16:37:41.234)
2. 🤏🏽 Hanseminator (01-17 16:40:41.234)
💀 behanc- (01-17 16:42:41.234)

Alternatively you could leave out the timestamp, since it will keep track of that regardless (even though I like the miliseconds :D):

1. ✅ kaapaaf
2. 🤏🏽 Hanseminator
💀 behanc-

**Comment by andjor** [comment]
I think it can, so that could be an idea. If people trust the system, we can leave out the timestamp☺️
